### PR TITLE
[Test-Only] Add test config and capabilities endpoints

### PR DESCRIPTION
**Pull request by dpakach**
Add HTTP api test for
- GET /cloud/capabilities
- GET /config

### CODE REVIEW

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/server/http/svc_test.go  21
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-ocs/pullRequest?prid=6186565&bid=20189162)

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm :+1:

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pkg/server/http/svc_test.go  21
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-ocs/pullRequest?prid=6186565&bid=20189162)

**Comment by phil-davis** [comment]
There is some problem with cloud.drone.io last night. It is not starting new jobs. We will need to rebase and force push again when cloud.drone.io starts working for us.

**Comment by dpakach** [comment]
Moved to https://github.com/owncloud/ocis/pull/635

**Pull request closed without merging**
